### ISSUE TITLE
Matching not correct.

### ISSUE THREAD

**Issue by fcastello** [betolj/ndpi-netfilter#1]
I think I found that protocols don't match the protocol name with the actual protocol being described.
I guess you fixed ewildgoose version by adding to xt_ndpi.h
NDPI_PROTOCOL_LONG_STRING
NDPI_PROTOCOL_SHORT_STRING

which does the matching of the protocol names in iptables -m ndpi --[protocol name]
This was usualy done in older versions of the nDPI library. But those constants are no longer part of the nDPI library. 
I will try with an older nDPI to get it to work. Otherwise it should be fixed to work with newer versions of the nDPI library since they don't match protocols with NDPI_PROTOCOL_LONG_STRING
NDPI_PROTOCOL_SHORT_STRING any more.

**Comment by mcitew** [comment]
I tested this too. I found it's working for some few protocols such as SSL, http, ftp. 

But one of the most important protocol, youtube ( specifically youtube over SSL ) is not working at all.

I just add an iptables rule, 

    iptables -I FORWARD -m ndpi --youtube 

Matches nothing. But when I run ndpiReader -i interface, it picks up youtube traffic

**Comment by Mile-Lile** [comment]
same for me. Did you founded solution?

**Comment by betolj** [comment]
Hi,

I'm working in a patch for the latest nDPI version and i will include support
for youtube too.
And i'm currently testing youtube detection - it seems to be working.

I'll *probably* update the repository tomorrow.

2015-06-11 4:49 GMT-04:00 Mile-Lile <notifications@github.com>:

**Comment by alrferreira** [comment]
Working to me when I enable first a SSL Rule. But Skype don't.

André Luiz R. Ferreira - NETDEEP 

-----Mensagem Original-----
De: "Humberto Jucá" <notifications@github.com>
Enviada em: ‎11/‎06/‎2015 22:45
Para: "betolj/ndpi-netfilter" <ndpi-netfilter@noreply.github.com>
Cc: "alrferreira" <alrferreira@netdeep.com.br>
Assunto: Re: [ndpi-netfilter] Matching not correct. (#1)

Hi,

I'm working in a patch for the latest nDPI version and i will include support
for youtube too.
And i'm currently testing youtube detection - it seems to be working.

I'll *probably* update the repository tomorrow.

2015-06-11 4:49 GMT-04:00 Mile-Lile <notifications@github.com>:

> same for me. Did you founded solution?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/betolj/ndpi-netfilter/issues/1#issuecomment-111045018>
> .
>

—
Reply to this email directly or view it on GitHub.
*** Secured by Netdeep ClearMail ***

**Comment by Mile-Lile** [comment]
@betolj 
Thx. appreciate it!

**Comment by betolj** [comment]
The "ndpi-netfilter" projects with logical structure based on "ewildgoose" model don't work well nowadays. 

1. Only one exclusive "conntrack notify" call: For this reason, it cann't be used in conjunction with nfnetlink. But, when you remove the nfnetlink kernel module, the conntrack application wont works anymore.

2. The web host detection depends on http or ssl protocols enabled: Youtube or Facebook protocols are not external modules (like /usr/src/nDPI/src/lib/protocols/*).

I finished xt_ndpi fixes today:
- Remove "conntrack notifier" from source code and include a new ndpi flow garbage collector for 3.x kernel series. Now, no longer need remove the nfnetlink kernel module to install xt_ndpi.
- Enable http and ssl protocol for youtube, facebook and others.

My tests, showed satisfactory results.
https://github.com/betolj/ndpi-netfilter

**Comment by Mile-Lile** [comment]
Thx again!

**Comment by hemanth4ap** [comment]
how to block particular  http/https urls by using ndpi
