### ISSUE TITLE
Add a new filter

### ISSUE THREAD

**Issue by adrienb4** [betolj/ndpi-netfilter#13]
Hi

How I can add from the compilation a new nDPI filter ?
What is the difference between 'NDPI_PROTOCOL_LONG_STRING' and 'NDPI_PROTOCOL_SHORT_STRING' ? 

Thank 

Adrien

**Comment by betolj** [comment]
Hi,
Unfortunately, the NDPI project received some API changes and this broke the compatibility with current ndpi-netfilter. And i also need to port the inet_pton function too.

The LONG and SHORT strings are used to identify NDPI ID and libxt "list" - into "nDPI/src/include/ndpi_protocol_ids.h" sequence.

**Comment by adrienb4** [comment]
I have build ntop and nDPI (with my own services). With NTOPNG all is ok (services match) but when i compile nDPI with 'ndpi-netfilter' my services not match. What is the procedure for add service to ndpi-netfilter compilation ?

**Comment by adrienb4** [comment]
Ok see #14 issue.
