### ISSUE TITLE
main.c bug

### ISSUE THREAD

**Issue by adrienb4** [betolj/ndpi-netfilter#14]
I have added a new NDPI_SERVICE in 'ndpi_protocol_ids.h' (like wikipedia and HTTP based protocol). This service is the last implemented (#define NDPI_LAST_IMPLEMENTED_PROTOCOL			190). 

If you build nDPI for iptables with your tool, this service is never matching because http protocol is not added.

In the current loop, the last protocol/service is never executed for added or not http support protocol

To correct this, apply this path in 'main.c' file (L787) :

```
        for (i = 0; i < NDPI_LAST_IMPLEMENTED_PROTOCOL +1; i++){
                atomic_set (&protocols_cnt[i], 0);

                // Set HTTP based protocols
                if ((i > 118 && i < 127) || (i > 139 && i < 146) || (i > 175 && i < 182 ) || i == 70 || i == 133) nfndpi_protocols_http[i]=1;
                else nfndpi_protocols_http[i]=0;
        }
```

**Comment by betolj** [comment]
Hi,
The better way to solve this question is modifying "#define NDPI_LAST_IMPLEMENTED_PROTOCOL" line to your new service (in ndpi_protocol_ids.h).

**Comment by adrienb4** [comment]
How does this fix the problem? In this case, the last protocol will never executed  :/

**Comment by adrienb4** [comment]
Sorry I think I deleted your comment :/

**Comment by betolj** [comment]
Dont worry, I removed last comment.
I will fix later. Thanks

**Comment by betolj** [comment]
Fix applied
