### ISSUE TITLE
libxt_ndpi.so

### ISSUE THREAD

**Issue by adrienb4** [betolj/ndpi-netfilter#19]
It's possible to copy the library to another router (same debian version and same hardware) ?
When I do this, I cant load xt_ndpi.so.

Thank

Adrien

**Comment by betolj** [comment]
You can... but you will have to resolve some dependences.
This require "/lib/modules/$(uname -r)/extra/xt_ndpi.ko" - and run "depmod -a" after copy.

And you need to copy the ndpi libraries too.
It can be harder work.

**Comment by adrienb4** [comment]
Thank for your response, it's work. I have to install NDPI 75 in routers. Copy libraries is more simpler.
You can add this method in the install doc ?

**Comment by kong156** [comment]
I didn't try with kernel modules, but there is a way to pack your build into a deb package.

**Comment by adrienb4** [comment]
Copy the files in this way present a risk?

**Comment by kong156** [comment]
No, but it can broke things when upgrading the kernel, and i think it's easier to deploy...

**Comment by adrienb4** [comment]
Yes i know this problem. You have a good idea to create a deb package for massive deployment.

**Comment by betolj** [comment]
Yes... you can build a deb package with checkinstall!

cd /usr/src/ndpi-netfilter/nDPI
./autogen.sh
sudo checkinstall

Then, copy /usr/src/ndpi-netfilter/nDPI/ndpi_<version>_amd64.deb to others firewalls.
