### ISSUE TITLE
modules not loading on nDPI >r8323

### ISSUE THREAD

**Issue by syadnom** [betolj/ndpi-netfilter#2]
I've pulled in nDPI release 8323 which does build and load, but it does nothing, no inspection.  I can get 5761 built with the mainline nDPI sources and they work.

(debian 7)

**Comment by betolj** [comment]
The "ndpi-netfilter" projects with logical structure based on "ewildgoose" model don't work well nowadays. 

1. Only one exclusive "conntrack notify" call: For this reason, it cann't be used in conjunction with nfnetlink. But, when you remove the nfnetlink kernel module, the conntrack application wont works anymore.

2. The web host detection depends on http or ssl protocols enabled: Youtube or Facebook protocols are not external modules (like /usr/src/nDPI/src/lib/protocols/*).

I finished xt_ndpi fixes today:
- Remove "conntrack notifier" from source code and include a new ndpi flow garbage collector for 3.x kernel series. Now, no longer need remove the nfnetlink kernel module to install xt_ndpi.
- Enable http and ssl protocol for youtube, facebook and others.

My tests, showed satisfactory results.
https://github.com/betolj/ndpi-netfilter
