### ISSUE TITLE
[NDPI] Internal error: protocol SSH/92 has been already registered

### ISSUE THREAD

**Issue by ziyilu** [betolj/ndpi-netfilter#21]
Hi,

I encountered an issue when I port ndpi-netfilter to ubuntu cloud image,
uname -a
Linux 3f6adc8e-6fd3-432a-ba83-19065e4eb00f 3.13.0-67-generic #110-Ubuntu SMP Fri Oct 23 13:24:41 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

The issue is,
for whatever protocol I add , for example, iptables -A FORWARD -m ndpi --ssh -j DROP
the kernel (dmesg) always complains "[NDPI] Internal error: protocol SSH/92 has been already registered"
I tried couple protocols, all with the same error.

Anyone encounter this issue before? Thanks.

Anything with the kernel module?
lsmod | grep table

iptable_nat            13011  1 
nf_nat_ipv4            13263  1 iptable_nat
nf_nat                 21841  4 ipt_MASQUERADE,nf_nat_ipv4,xt_nat,iptable_nat
nf_conntrack           97202  7 xt_ndpi,ipt_MASQUERADE,nf_nat,nf_nat_ipv4,xt_conntrack,iptable_nat,nf_conntrack_ipv4
iptable_filter         12810  1 
ip_tables              27239  2 iptable_filter,iptable_nat
x_tables               34059  8 xt_ndpi,ip_tables,xt_tcpudp,ipt_MASQUERADE,xt_conntrack,xt_LOG,xt_nat,iptable_filter

**Comment by betolj** [comment]
Fix applied!

**Comment by rsweerarathna** [comment]
I m getting the same error. but not for all the protocols. DNS SSL and Bittorrent i get this error.
I got the latest version of the source code 29th of Feb.
Still getting the same error. Any idea what's happening?
