### ISSUE TITLE
kernel patch doesn't apply

### ISSUE THREAD

**Issue by syadnom** [betolj/ndpi-netfilter#3]
Would you mind telling me the exact kernel version your fork of the ndpi-netfilter was last built against as working?  I can't get the patch to apply to 2.6.32 which is the stock deb6 kernel (maybe I'm patching wrong?) so though I can get ndpi-netfilter compiled and loaded, it wont match anything.  I did recompile the kernel as instruct but without the patch.
Thanks

**Comment by betolj** [comment]
The "ndpi-netfilter" projects with logical structure based on "ewildgoose" model don't work well nowadays. 

1. Only one exclusive "conntrack notify" call: For this reason, it cann't be used in conjunction with nfnetlink. But, when you remove the nfnetlink kernel module, the conntrack application wont works anymore.

2. The web host detection depends on http or ssl protocols enabled: Youtube or Facebook protocols are not external modules (like /usr/src/nDPI/src/lib/protocols/*).

I finished xt_ndpi fixes today:
- Remove "conntrack notifier" from source code and include a new ndpi flow garbage collector for 3.x kernel series. Now, no longer need remove the nfnetlink kernel module to install xt_ndpi.
- Enable http and ssl protocol for youtube, facebook and others.

My tests, showed satisfactory results.
https://github.com/betolj/ndpi-netfilter

**Comment by syadnom** [comment]
betolj, does this mean that ndpi current can be used with ndpi-netfilter?

**Comment by betolj** [comment]
Yes .. the project was upgraded to the latest nDPI version.

**Comment by syadnom** [comment]
awesome, I will take it for a spin tomorrow!

**Comment by syadnom** [comment]
I've built ndpi and ndpi-netfilter both from trunk on ubuntu 14.04 x64

I'm unable to load the module, 
modprobe: ERROR: could not insert 'xt_ndpi': Unknown symbol in module, or unknown parameter (see dmesg)

**Comment by syadnom** [comment]
I do see a couple warnings in the build:
WARNING: "ndpi_search_kakaotalk_voice" [/usr/src/ndpi-netfilter/trunk/src/xt_ndpi.ko] undefined!
WARNING: "ndpi_search_eaq" [/usr/src/ndpi-netfilter/trunk/src/xt_ndpi.ko] undefined!
  LD [M]  /usr/src/ndpi-netfilter/trunk/src/xt_ndpi.ko
make[2]: Leaving directory `/usr/src/linux-headers-3.13.0-55-generic'
rm -r ndpi_cpy
make[1]: Leaving directory `/usr/src/ndpi-netfilter/trunk/src'


here is the dmesg output:
[  381.317982] nf_conntrack version 0.5.0 (16384 buckets, 65536 max)
[  381.319381] xt_ndpi: module verification failed: signature and/or  required key missing - tainting kernel
[  381.319459] xt_ndpi: Unknown symbol ndpi_search_eaq (err 0)
[  381.319467] xt_ndpi: Unknown symbol ndpi_search_kakaotalk_voice (err 0)
[  395.498339] xt_ndpi: Unknown symbol ndpi_search_eaq (err 0)
[  395.498374] xt_ndpi: Unknown symbol ndpi_search_kakaotalk_voice (err 0)
[  400.135331] xt_ndpi: Unknown symbol ndpi_search_eaq (err 0)
[  400.135365] xt_ndpi: Unknown symbol ndpi_search_kakaotalk_voice (err 0)
[  434.523824] xt_ndpi: Unknown symbol ndpi_search_eaq (err 0)
[  434.523858] xt_ndpi: Unknown symbol ndpi_search_kakaotalk_voice (err 0)
[  483.377801] xt_ndpi: Unknown symbol ndpi_search_eaq (err 0)
[  483.377836] xt_ndpi: Unknown symbol ndpi_search_kakaotalk_voice (err 0)
[  512.407602] xt_ndpi: Unknown symbol ndpi_search_eaq (err 0)
[  512.407623] xt_ndpi: Unknown symbol ndpi_search_kakaotalk_voice (err 0)
[  961.657982] xt_ndpi: Unknown symbol ndpi_search_eaq (err 0)
[  961.658016] xt_ndpi: Unknown symbol ndpi_search_kakaotalk_voice (err 0)
[ 1000.082087] xt_ndpi: Unknown symbol ndpi_search_eaq (err 0)
[ 1000.082122] xt_ndpi: Unknown symbol ndpi_search_kakaotalk_voice (err 0)

**Comment by syadnom** [comment]
I removed kakaotalk and eaq from ndpi which allowed my to build and load xt_ndpi, but now I get a kernel panic whenever iptables loads the ndpi module.

**Comment by syadnom** [comment]
dmesg shows this when loading the module

[ 2689.841269] xt_ndpi 2.0 (nDPI wrapper module).
[ 2689.849190] [NDPI] ndpi_string_to_automa(protoId=193): INTERNAL ERROR
[ 2689.849195] [NDPI] ndpi_string_to_automa(protoId=195): INTERNAL ERROR
[ 2689.849260] [NDPI] ndpi_string_to_automa(protoId=195): INTERNAL ERROR
[ 2689.849496] [NDPI] ndpi_init_protocol_defaults(missing protoId=194) INTERNAL ERROR: not all protocols have been initialized

**Comment by syadnom** [comment]
sorry for the string of comments.....

iptables -m ndpi --help segfaults

ndpi match options:
--ftp Match for FTP_CONTROL protocol packets.
--pop Match for MAIL_POP protocol packets.
<-- truncated list -->
--whatsapp_voice Match for WHATSAPP_VOICE protocol packets.
--dpi_check Match for CHECK protocol packets.
Segmentation fault (core dumped)

**Comment by syadnom** [comment]
opened a new issue, please ignore my previous few comments and see updated issue #8
