### ISSUE TITLE
nDPInetfilter module does not work for TCP protocols such as SSH,TELNET while ndpiReader works

### ISSUE THREAD

**Issue by shahanshasalim** [betolj/ndpi-netfilter#55]
My program is a server client application which forwards packet from ethernet to tunnel interface. In this program a custom payload is added to the end of TELNET/FTP/SSH Packet when it goes through the tunnel.At the other end this payload is removed. My aim is to detect the packet at tunnel using ndpi_netfilter.For this I compiled ndpi_netfilter and loaded it. When I add filter to drop SSH, TELNET,FTP it doesn't work(ndpi_netfilter module does not identify the packet correctly).But when I run ndpiReader it detects everything correctly.If the custom payload is not there then ndpi_netfilter module also detects the packets. I could not understand the reason for this.

My iptables rule is like this:
iptables -t mangle -A PREROUTING -i tun2 -m ndpi --ssh -j DROP
iptables -t mangle -A POSTROUTING -o tun2 -m ndpi --ssh -j DROP

**Comment by elico** [comment]
@shehan492 on what OS?

**Comment by kong156** [comment]
As discussed before across multiple topics here, you  should use ACCEPT rules instead of DROP ruls an check the counters to see if the traffic is identified as expected.
