### ISSUE TITLE
Doesn't work with the latest nDPI build 9132

### ISSUE THREAD

**Issue by kong156** [betolj/ndpi-netfilter#7]
Also noticed that youtube protocol is not recognized!?

**Comment by mcitew** [comment]
nDPI revision after 9089 needs further work to separate the usermode code from kernel mode code. Yes, it can be compiled, but with a patch.

**Comment by betolj** [comment]
The "ndpi-netfilter" projects with logical structure based on "ewildgoose" model don't work well nowadays.

    Only one exclusive "conntrack notify" call: For this reason, it cann't be used in conjunction with nfnetlink. But, when you remove the nfnetlink kernel module, the conntrack application wont works anymore.

    The web host detection depends on http or ssl protocols enabled: Youtube or Facebook protocols are not external modules (like /usr/src/nDPI/src/lib/protocols/*).

I finished xt_ndpi fixes today:

    Remove "conntrack notifier" from source code and include a new ndpi flow garbage collector for 3.x kernel series. Now, no longer need remove the nfnetlink kernel module to install xt_ndpi.
    Enable http and ssl protocol for youtube, facebook and others.

My tests, showed satisfactory results.
https://github.com/betolj/ndpi-netfilter

**Comment by betolj** [comment]
The "ndpi-netfilter" projects with logical structure based on "ewildgoose" model don't work well nowadays. 

1. Only one exclusive "conntrack notify" call: For this reason, it cann't be used in conjunction with nfnetlink. But, when you remove the nfnetlink kernel module, the conntrack application wont works anymore.

2. The web host detection depends on http or ssl protocols enabled: Youtube or Facebook protocols are not external modules (like /usr/src/nDPI/src/lib/protocols/*).

I finished xt_ndpi fixes today:
- Remove "conntrack notifier" from source code and include a new ndpi flow garbage collector for 3.x kernel series. Now, no longer need remove the nfnetlink kernel module to install xt_ndpi.
- Enable http and ssl protocol for youtube, facebook and others.

My tests, showed satisfactory results.
https://github.com/betolj/ndpi-netfilter
